- name: mxcl/Xcodebuild
  # You may pin to the exact commit or the version.
  # uses: mxcl/xcodebuild@d76d476983823aac9a5f66042456cad90fc7393d
  uses: mxcl/xcodebuild@v1.9.2
  with:
    # A semantic version range, eg. ^10, ~10.3 or 10.3.1
Leave unset for the image‑default.

    xcode: # optional
    # A semantic version range, eg. ^5, ~5.4 or 5.4.1
    swift: # optional
    # Either `iOS`, `tvOS`, `macOS`, `watchOS` or (more rarely)
`mac-catalyst`
Leave unset and `xcodebuild` decides itself.

    platform: # optional
    # * The most common actions are `test`, `build`.
* See the `xcodebuild` manual for available actions.
* Specifying `none` skips the explicit `xcodebuild` step allowing you
  to use this (GitHub) Action solely for selecting an Xcode version.
* Specifying `''`, `null` or `~` will cause xcodebuild to behave as it
  does without an action specified (usually `build`)

    action: # optional, default is test
    # Enables code coverage
    code-coverage: # optional, default is false
    # A Base64-encoded certificate to be installed to the macOS Keychain for
code signing. It is removed from the keychain in the post action. This
certificate should correspond to the `CODE_SIGN_IDENTITY` specified in
your project or to the `code-sign-identity` input. Pass this in as a
GitHub Encrypted Secret. Requires macOS and
`code-sign-certificate-passphrase`.

    code-sign-certificate: # optional
    # The passphrase used to protect the code signing certificate. Pass this in
as a GitHub Encrypted Secret.

    code-sign-certificate-passphrase: # optional
    # Identity to be used for code signing. If your project specifies a
`CODE_SIGN_IDENTITY`, this will override it.

    code-sign-identity: # optional
    # …
    working-directory: # optional
    # Typically `Release` or `Debug`.
Leave unset and `xcodebuild` decides itself.

    configuration: # optional
    # A scheme defined by an Xcode project or workspace.
If not specified, xcodebuild builds only the first target.

    scheme: # optional
    # Fails the build if any warnings in *non test targets*.
    warnings-as-errors: # optional, default is false
    # One of `xcpretty`, `quiet` or `verbose`.
    verbosity: # optional, default is xcpretty
    # One of `always` or `on-failure`.
Consider `always` if you want access to your coverage-reports.
Beware that artifacts count against your GitHub Actions storage limits.

    upload-logs: # optional, default is on-failure
